#!/bin/bash

#apt-get install MySQL-python
yum -y install MySQL-python
pip install redis lxml

target=$(pypath)
cur=$(pwd)

ln -fs $cur $target

echo "ln -s $cur pylib $target"

# if python lib not the system lib(install from yum not avalible)
#yum -y install mysql-devel
#cd data
#unzip MySQL-python-1.2.5.zip
#cd MySQL-python-1.2.5
#python ./setup.py install
#cd ..
#cd ..
